# -*- coding: utf-8 -*-
# vim: ft=yaml
---
include:
  - project: EOLE/infra/ci-tools
    ref: stable
    file: /templates/Rules.yaml
  - project: EOLE/infra/ci-tools
    ref: stable
    file: /templates/Runners/apps.education-docker.yaml
  - project: EOLE/infra/ci-tools
    ref: stable
    file: /templates/Git.yaml
  - project: EOLE/infra/ci-tools
    ref: stable
    file: /templates/Semantic-release.yaml

variables:
  # `ci-tools` default branch is `stable`
  STABLE_BRANCH: master

stages:
  - initial-checks
  - release

###############################################################################
# `initial-checks` stage: `commitlint`
###############################################################################
commitlint:
  stage: initial-checks
  extends: .git:commitlint


###############################################################################
# `release` stage: `new release`, `testing prerelease`
###############################################################################
new release:
  extends:
    - .semantic-release:stable
    - .on-stable

testing prerelease:
  extends:
    - .semantic-release:testing
    - .on-testing
